# Generated by Django 5.1.4 on 2025-02-06 12:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMusicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_count', models.PositiveIntegerField(default=1)),
                ('last_played_at', models.DateTimeField(auto_now=True)),
                ('total_listen_time', models.DurationField(default=datetime.timedelta(0))),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plays', to='music.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_played_at'],
                'unique_together': {('user', 'music')},
            },
        ),
    ]
