# Generated by Django 5.1.4 on 2025-02-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusichistory',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermusichistory',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
