version: '3.8'

services:
  web:
    build: .
    container_name: backend
    restart: always  # Automatically restart the service if it crashes
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: gunicorn WaveBackend.wsgi:application --bind 0.0.0.0:8000 --worker>

  postgres:
    image: postgres:15-alpine
    container_name: backend-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:  # Ensure Postgres is healthy before the app starts
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      retries: 5

  redis:
    image: redis:alpine
    container_name: backend-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning  # Optimize Redis for >
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

volumes:
  postgres_data:
  static_volume:

