# Generated by Django 5.1.4 on 2025-01-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='banner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='banner_photo/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artist_photo/'),
        ),
    ]
