# Generated by Django 5.1.4 on 2025-03-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='banner_photo',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='photo',
        ),
    ]
