"""
Playlist models for the Wave platform.

Supports user-created and system-generated playlists with ordered tracks.
"""

from __future__ import annotations

from django.core.validators import FileExtensionValidator
from django.db import models

from music.models import Music
from users.models import CustomUser


class Playlist(models.Model):
    """
    A collection of tracks, either user-created or auto-generated by
    the recommendation engine.
    """

    created_by = models.ForeignKey(
        CustomUser,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="created_playlists",
    )
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    is_public = models.BooleanField(
        default=True,
        help_text="Whether this playlist is publicly available.",
    )
    cover_photo = models.ImageField(
        upload_to="playlist_covers/",
        validators=[FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png"])],
    )
    tracks = models.ManyToManyField(
        Music,
        through="PlaylistTrack",
        related_name="playlists",
    )
    duration = models.PositiveIntegerField(
        default=0,
        help_text="Total duration of the playlist in seconds.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_system_created = models.BooleanField(
        default=False,
        help_text="Indicates if playlist is system-generated.",
    )

    class Meta:
        verbose_name = "playlist"
        verbose_name_plural = "playlists"
        ordering = ["-created_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["name", "created_by"],
                name="unique_playlist_per_user",
            )
        ]

    def __str__(self) -> str:
        creator = self.created_by.username if self.created_by else "System"
        return f"Playlist: {self.name} by {creator}"


class PlaylistTrack(models.Model):
    """Through model linking a track to a playlist at a specific position."""

    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    music = models.ForeignKey(Music, on_delete=models.CASCADE)
    track_number = models.PositiveIntegerField()

    class Meta:
        verbose_name = "playlist track"
        verbose_name_plural = "playlist tracks"
        ordering = ["track_number"]
        constraints = [
            models.UniqueConstraint(
                fields=["playlist", "music", "track_number"],
                name="unique_playlist_track_position",
            )
        ]

    def __str__(self) -> str:
        return f"{self.playlist.name} #{self.track_number}: {self.music.name}"
