# Generated by Django 5.1.4 on 2025-03-05 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0004_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('live', 'Live'), ('ended', 'Ended')], default='preparing', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_viewers', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestreams', to='artists.artist')),
            ],
        ),
    ]
