# Generated by Django 5.0.6 on 2025-01-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='genre',
        ),
    ]
