# Generated by Django 5.0.6 on 2025-01-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_remove_playlist_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='banner_img',
        ),
    ]
