# Generated by Django 5.0.14 on 2026-03-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_album_options_alter_albumtrack_options_and_more'),
        ('playlist', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'playlist', 'verbose_name_plural': 'playlists'},
        ),
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'ordering': ['track_number'], 'verbose_name': 'playlist track', 'verbose_name_plural': 'playlist tracks'},
        ),
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Total duration of the playlist in seconds.'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this playlist is publicly available.'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_system_created',
            field=models.BooleanField(default=False, help_text='Indicates if playlist is system-generated.'),
        ),
        migrations.AddConstraint(
            model_name='playlisttrack',
            constraint=models.UniqueConstraint(fields=('playlist', 'music', 'track_number'), name='unique_playlist_track_position'),
        ),
    ]
