# Generated by Django 5.1.4 on 2025-02-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_playlist_unique_playlist_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_system_created',
            field=models.BooleanField(default=False, help_text='Indicates if playlist is system-generated'),
        ),
    ]
