# Generated by Django 5.1.4 on 2025-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumplan',
            name='features',
            field=models.TextField(blank=True, help_text='Store features as pipe-separated values'),
        ),
    ]
