# Generated by Django 5.0.14 on 2026-03-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_alter_premiumplan_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumplan',
            options={'ordering': ['display_order', 'price'], 'verbose_name': 'premium plan', 'verbose_name_plural': 'premium plans'},
        ),
        migrations.AlterModelOptions(
            name='razorpaytransaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which plans are shown to users.'),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='duration_days',
            field=models.PositiveIntegerField(help_text='Duration in days.'),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='duration_label',
            field=models.CharField(help_text="Human-readable label (e.g. '1 Week', '3 Months').", max_length=50),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='features',
            field=models.TextField(blank=True, help_text='Pipe-separated feature list.'),
        ),
    ]
