# Generated by Django 5.1.4 on 2025-03-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0002_remove_livestream_artist_livestream_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
