# Generated by Django 5.1.4 on 2025-03-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0005_remove_streamparticipant_left_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
