# Generated by Django 5.1.4 on 2025-03-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='initiated', max_length=20)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('counted_as_play', models.BooleanField(default=False)),
            ],
        ),
    ]
