# Generated by Django 5.1.4 on 2025-03-14 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listening_history', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music'),
        ),
    ]
