# Generated by Django 5.1.4 on 2025-02-22 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening_history', '0001_initial'),
        ('music', '0006_remove_streamingsession_music_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playcount',
            unique_together={('user', 'music')},
        ),
        migrations.AddIndex(
            model_name='playcount',
            index=models.Index(fields=['user', 'last_played'], name='listening_h_user_id_936f00_idx'),
        ),
        migrations.AddIndex(
            model_name='playcount',
            index=models.Index(fields=['music', 'count'], name='listening_h_music_i_015796_idx'),
        ),
    ]
