# Generated by Django 5.1.4 on 2025-03-11 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listening_history', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='playsession',
            index=models.Index(fields=['play_id'], name='listening_h_play_id_ebad3c_idx'),
        ),
        migrations.AddIndex(
            model_name='playsession',
            index=models.Index(fields=['user', 'music'], name='listening_h_user_id_ddbf08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playsession',
            unique_together={('user', 'play_id')},
        ),
    ]
