# Generated by Django 5.1.4 on 2025-09-07 09:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_remove_artist_banner_photo_remove_artist_photo'),
        ('listening_history', '0003_initial'),
        ('music', '0006_userpreference_streamingfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistPlayCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_plays', models.PositiveIntegerField(default=0)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='play_stats', to='artists.artist')),
            ],
        ),
        migrations.CreateModel(
            name='MusicActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('play', 'Play'), ('complete', 'Complete')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='music.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MusicPlayCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_plays', models.PositiveIntegerField(default=0)),
                ('music', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='play_stats', to='music.music')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_plays', models.PositiveIntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='artists.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_played'],
                'unique_together': {('user', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='RecentlyPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_played', models.DateTimeField(default=django.utils.timezone.now)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_played', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_played'],
                'unique_together': {('user', 'music')},
            },
        ),
    ]
