# Generated by Django 5.1.4 on 2025-03-02 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening_history', '0003_playcount_total_play_duration_and_more'),
        ('music', '0007_equalizerpreset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='playhistory',
            name='listening_h_session_f03242_idx',
        ),
        migrations.RemoveField(
            model_name='playcount',
            name='total_play_duration',
        ),
        migrations.RemoveField(
            model_name='playhistory',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='playhistory',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='playhistory',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='playhistory',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='playcount',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='playcount',
            name='last_played',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_counts', to='music.music'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
