# Generated by Django 5.1.4 on 2025-03-02 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening_history', '0004_remove_playhistory_listening_h_session_f03242_idx_and_more'),
        ('music', '0007_equalizerpreset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playhistory',
            name='counted_as_play',
            field=models.BooleanField(default=True, help_text='Whether this play met criteria to count as a legitimate play'),
        ),
        migrations.AddField(
            model_name='playhistory',
            name='play_status',
            field=models.CharField(choices=[('initiated', 'Playback Initiated'), ('completed', 'Playback Completed'), ('aborted', 'Playback Aborted')], default='initiated', max_length=20),
        ),
        migrations.AddField(
            model_name='playhistory',
            name='played_duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds the track was played', null=True),
        ),
        migrations.AddIndex(
            model_name='playhistory',
            index=models.Index(fields=['counted_as_play'], name='listening_h_counted_fb68bb_idx'),
        ),
    ]
