# Generated by Django 5.1.4 on 2025-09-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listening_history', '0004_artistplaycount_musicactivity_musicplaycount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaySession',
        ),
    ]
