# Generated by Django 5.0.14 on 2026-03-10 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_alter_artist_options_alter_follow_options_and_more'),
        ('listening_history', '0005_delete_playsession'),
        ('music', '0007_alter_album_options_alter_albumtrack_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistactivity',
            options={'ordering': ['-last_played'], 'verbose_name': 'artist activity', 'verbose_name_plural': 'artist activities'},
        ),
        migrations.AlterModelOptions(
            name='artistplaycount',
            options={'verbose_name': 'artist play count', 'verbose_name_plural': 'artist play counts'},
        ),
        migrations.AlterModelOptions(
            name='musicactivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'music activity', 'verbose_name_plural': 'music activities'},
        ),
        migrations.AlterModelOptions(
            name='musicplaycount',
            options={'verbose_name': 'track play count', 'verbose_name_plural': 'track play counts'},
        ),
        migrations.AlterModelOptions(
            name='recentlyplayed',
            options={'ordering': ['-last_played'], 'verbose_name': 'recently played', 'verbose_name_plural': 'recently played'},
        ),
        migrations.AlterUniqueTogether(
            name='artistactivity',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recentlyplayed',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='artistactivity',
            constraint=models.UniqueConstraint(fields=('user', 'artist'), name='unique_user_artist_activity'),
        ),
        migrations.AddConstraint(
            model_name='recentlyplayed',
            constraint=models.UniqueConstraint(fields=('user', 'music'), name='unique_user_recently_played'),
        ),
    ]
