# Generated by Django 5.1.4 on 2025-03-03 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening_history', '0005_playhistory_counted_as_play_playhistory_play_status_and_more'),
        ('music', '0008_alter_album_name_alter_music_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='initiated', max_length=20)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('counted_as_play', models.BooleanField(default=False)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['play_id'], name='listening_h_play_id_ebad3c_idx'), models.Index(fields=['user', 'music'], name='listening_h_user_id_ddbf08_idx')],
                'unique_together': {('user', 'play_id')},
            },
        ),
    ]
