# Generated by Django 5.0.14 on 2026-03-24 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_alter_artist_options_alter_follow_options_and_more'),
        ('listening_history', '0006_alter_artistactivity_options_and_more'),
        ('music', '0007_alter_album_options_alter_albumtrack_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('playlist', 'Playlist'), ('album', 'Album'), ('artist', 'Artist'), ('single', 'Single'), ('search', 'Search'), ('recommendation', 'Recommendation')], default='single', max_length=20)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_played_at', models.DateTimeField(auto_now=True)),
                ('play_count', models.PositiveIntegerField(default=1)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listening_histories', to='music.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_histories', to='artists.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_histories', to='music.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'listening history',
                'verbose_name_plural': 'listening histories',
                'ordering': ['-last_played_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='listeninghistory',
            constraint=models.UniqueConstraint(fields=('user', 'track'), name='unique_user_track_history'),
        ),
    ]
