# Generated by Django 5.1.4 on 2025-03-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listening_history', '0006_playsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playhistory',
            name='music',
        ),
        migrations.RemoveField(
            model_name='playhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='PlayCount',
        ),
        migrations.DeleteModel(
            name='PlayHistory',
        ),
    ]
