---
name: CI/CD Pipeline for Backend

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  test:
    runs-on: self-hosted
    if: >
      github.event_name != 'pull_request' || 
      github.event.pull_request.merged != true

    steps:
      - uses: actions/checkout@v3

      - name: Run Tests in Docker
        run: |
          cd Wave/Backend
          docker-compose --profile ci up --build --exit-code-from ci
          docker-compose --profile ci down

  deploy:
    runs-on: self-hosted
    needs: test
    if: >
      github.ref == 'refs/heads/main' || 
      (github.event_name == 'pull_request' && 
      github.event.pull_request.merged == true && 
      github.event.pull_request.base.ref == 'main')

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Backend
        run: |
          cd /home/ubuntu/Wave/Backend
          git pull origin main
          sudo docker-compose up -d --build
          sudo docker exec backend python manage.py migrate
          sudo service nginx restart
          sudo docker image prune -a -f