# Generated by Django 5.1.4 on 2024-12-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_unlisted',
        ),
    ]
