# Generated by Django 5.1.4 on 2025-03-11 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0003_initial'),
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equalizerpreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equalizer_presets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musical_works', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='music',
            name='genres',
            field=models.ManyToManyField(related_name='musical_works', to='music.genre'),
        ),
        migrations.AddField(
            model_name='albumtrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music'),
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(related_name='albums', through='music.AlbumTrack', to='music.music'),
        ),
        migrations.AlterUniqueTogether(
            name='equalizerpreset',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='albumtrack',
            unique_together={('album', 'track_number')},
        ),
    ]
