# Generated by Django 5.0.6 on 2025-01-03 11:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_banner_photo_artist_photo'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover_photo', models.ImageField(upload_to='music_covers/')),
                ('audio_file', models.FileField(upload_to='music/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'aac'])])),
                ('video_file', models.FileField(blank=True, null=True, upload_to='music_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])])),
                ('duration', models.DurationField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('release_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musical_works', to='artists.artist')),
                ('genres', models.ManyToManyField(related_name='musical_works', to='music.genre')),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
