# Generated by Django 5.0.6 on 2025-01-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Total duration of the album in seconds'),
        ),
        migrations.AlterField(
            model_name='music',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this music is publicly available'),
        ),
    ]
