# Generated by Django 5.1.4 on 2025-03-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equalizerpreset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='equalizerpreset',
            name='band_31',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equalizerpreset',
            name='band_62',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equalizerpreset',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_125',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_16k',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_1k',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_250',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_2k',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_4k',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_500',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_8k',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='equalizerpreset',
            name='band_32',
        ),
        migrations.RemoveField(
            model_name='equalizerpreset',
            name='band_64',
        ),
        migrations.RemoveField(
            model_name='equalizerpreset',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='equalizerpreset',
            name='user',
        ),
    ]
