# Generated by Django 5.0.6 on 2025-01-04 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(default=1, upload_to='music/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'aac'])]),
            preserve_default=False,
        ),
    ]
