# Generated by Django 5.1.4 on 2025-02-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_musicplayhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='duration',
            field=models.CharField(help_text='Duration in format HH:MM:SS.MMMMMM', max_length=20),
        ),
    ]
