# Generated by Django 5.1.4 on 2025-03-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_equalizerpreset_unique_together_and_more'),
    ]

    operations = [
    ]
