# Generated by Django 5.0.6 on 2025-01-06 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_music_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='genres',
        ),
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='musical_works', to='music.genre'),
            preserve_default=False,
        ),
    ]
