# Generated by Django 5.1.4 on 2025-03-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_create_default_presets'),
    ]

    operations = [
    ]
