# Generated by Django 5.1.4 on 2025-02-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_album_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicplayhistory',
            name='duration_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Total duration of the album in seconds'),
        ),
    ]
