# Generated by Django 5.0.6 on 2025-01-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_music_genres_music_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='genre',
        ),
        migrations.AddField(
            model_name='music',
            name='genres',
            field=models.ManyToManyField(related_name='musical_works', to='music.genre'),
        ),
    ]
