# Generated by Django 5.1.4 on 2025-02-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_musicplayhistory_duration_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamingsession',
            name='music',
        ),
        migrations.RemoveField(
            model_name='streamingsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='MusicPlayHistory',
        ),
        migrations.DeleteModel(
            name='StreamingSession',
        ),
    ]
