# Generated by Django 5.1.4 on 2025-08-26 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_create_default_presets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('lossless', 'Lossless')], default='low', help_text="User's preferred streaming quality", max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreamingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('lossless', 'Lossless')], max_length=20)),
                ('hls_playlist', models.URLField(help_text='URL to the .m3u8 file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_files', to='music.music')),
            ],
            options={
                'unique_together': {('music', 'quality')},
            },
        ),
    ]
