# Generated by Django 5.0.14 on 2026-03-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_userpreference_streamingfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-created_at'], 'verbose_name': 'album', 'verbose_name_plural': 'albums'},
        ),
        migrations.AlterModelOptions(
            name='albumtrack',
            options={'ordering': ['track_number'], 'verbose_name': 'album track', 'verbose_name_plural': 'album tracks'},
        ),
        migrations.AlterModelOptions(
            name='equalizerpreset',
            options={'ordering': ['name'], 'verbose_name': 'equalizer preset', 'verbose_name_plural': 'equalizer presets'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-created_at'], 'verbose_name': 'track', 'verbose_name_plural': 'tracks'},
        ),
        migrations.AlterModelOptions(
            name='streamingfile',
            options={'verbose_name': 'streaming file', 'verbose_name_plural': 'streaming files'},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'user preference', 'verbose_name_plural': 'user preferences'},
        ),
        migrations.AlterUniqueTogether(
            name='albumtrack',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='streamingfile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='album',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Total duration of the album in seconds.'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this album is publicly available.'),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_125',
            field=models.FloatField(default=0.0, help_text='125 Hz'),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_16k',
            field=models.FloatField(default=0.0, help_text='16 kHz'),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_1k',
            field=models.FloatField(default=0.0, help_text='1 kHz'),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_250',
            field=models.FloatField(default=0.0, help_text='250 Hz'),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_2k',
            field=models.FloatField(default=0.0, help_text='2 kHz'),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_31',
            field=models.FloatField(default=0.0, help_text='31 Hz'),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_4k',
            field=models.FloatField(default=0.0, help_text='4 kHz'),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_500',
            field=models.FloatField(default=0.0, help_text='500 Hz'),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_62',
            field=models.FloatField(default=0.0, help_text='62 Hz'),
        ),
        migrations.AlterField(
            model_name='equalizerpreset',
            name='band_8k',
            field=models.FloatField(default=0.0, help_text='8 kHz'),
        ),
        migrations.AlterField(
            model_name='music',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this music is publicly available.'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_quality',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('lossless', 'Lossless')], default='low', help_text="User's preferred streaming quality.", max_length=20),
        ),
        migrations.AddConstraint(
            model_name='albumtrack',
            constraint=models.UniqueConstraint(fields=('album', 'track_number'), name='unique_album_track_number'),
        ),
        migrations.AddConstraint(
            model_name='streamingfile',
            constraint=models.UniqueConstraint(fields=('music', 'quality'), name='unique_music_quality'),
        ),
    ]
