# Generated by Django 5.1.4 on 2025-02-28 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_streamingsession_music_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EqualizerPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('band_32', models.IntegerField(default=0)),
                ('band_64', models.IntegerField(default=0)),
                ('band_125', models.IntegerField(default=0)),
                ('band_250', models.IntegerField(default=0)),
                ('band_500', models.IntegerField(default=0)),
                ('band_1k', models.IntegerField(default=0)),
                ('band_2k', models.IntegerField(default=0)),
                ('band_4k', models.IntegerField(default=0)),
                ('band_8k', models.IntegerField(default=0)),
                ('band_16k', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equalizer_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
