# Generated by Django 5.1.4 on 2025-03-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_equalizerpreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
