# Generated by Django 5.0.6 on 2025-01-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_album_albumtrack_album_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this music is publicly available'),
        ),
    ]
